# Build settings
permalink: /blog/:year/:title/
markdown: kramdown
highlighter: pygments
plugins: [jekyll-paginate]

host: 0.0.0.0

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _sass
  style: compressed # expanded

# SEO settings
title: Kim Sumin
description: "A free Jekyll theme for download"
keywords: "Jekyll, theme, free, download, SEO, blog, web"
url: http://kimsumin.me
baseurl: "/kimsumin"

google_analytics: UA-52446115-1
repo: https://github.com/kimmyhigh/kimmyhigh.github.io
disqus_shortname: ""
disqus_site_shortname: ""

# Author settings
author:
  name: Sumin Kim
  job: International Business Management Student
  bio: ""
  thumb: /images/author.jpg
  email: hello@kimsumin.me
  url: https://kimsumin.me/
  github: https://github.com/kimmyhigh
  twitter: 
  facebook: 
  linkedin: 

# navbar pages
navbar:
  - slug: about
    title: About
  - slug: icons
    title: Icons
  - slug: blog
    title: Blog

exclude: ["config.rb", "src", "Gemfile", "Gemfile.lock", "package.json","README.md", "Rakefile"]
